#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ] || [ -n "${HASHED_PASSWORD}" ]; then
    AUTH="${PASSWORD}"
else
    AUTH="none"
    echo "starting with no password"
fi

if [ -z ${PROXY_DOMAIN+x} ]; then
    PROXY_DOMAIN_ARG=""
else
    PROXY_DOMAIN_ARG="--proxy-domain=${PROXY_DOMAIN}"
fi

if [ -z ${CODE_PORT} ]; then
    CODE_PORT_ARG="--bind-addr=0.0.0.0:2999"
else
    CODE_PORT_ARG="--bind-addr 0.0.0.0:${CODE_PORT}"
fi

/usr/local/bin/code-server \
    "${CODE_PORT_ARG}" \
    --user-data-dir /home/.config/data \
    --extensions-dir /home/.config/extensions \
    --disable-telemetry \
    --auth "${AUTH}" \
    "${PROXY_DOMAIN_ARG}" \
    /home/workspace
